/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/bookmarks': RouteRecordInfo<
      '/bookmarks',
      '/bookmarks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/drafts/private-thoughts': RouteRecordInfo<
      '/drafts/private-thoughts',
      '/drafts/private-thoughts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/illustrations': RouteRecordInfo<
      '/illustrations',
      '/illustrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media': RouteRecordInfo<
      '/media',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai-tools-guide-2026': RouteRecordInfo<
      '/posts/ai-tools-guide-2026',
      '/posts/ai-tools-guide-2026',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/find-enough-in-many-worlds': RouteRecordInfo<
      '/posts/find-enough-in-many-worlds',
      '/posts/find-enough-in-many-worlds',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-world': RouteRecordInfo<
      '/posts/hello-world',
      '/posts/hello-world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/private-diary': RouteRecordInfo<
      '/posts/private-diary',
      '/posts/private-diary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/presentations': RouteRecordInfo<
      '/presentations',
      '/presentations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/private': RouteRecordInfo<
      '/private',
      '/private',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use': RouteRecordInfo<
      '/use',
      '/use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/bookmarks.md': {
      routes:
        | '/bookmarks'
      views:
        | never
    }
    'pages/drafts/private-thoughts.md': {
      routes:
        | '/drafts/private-thoughts'
      views:
        | never
    }
    'pages/illustrations.md': {
      routes:
        | '/illustrations'
      views:
        | never
    }
    'pages/media.md': {
      routes:
        | '/media'
      views:
        | never
    }
    'pages/notes.md': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/ai-tools-guide-2026.md': {
      routes:
        | '/posts/ai-tools-guide-2026'
      views:
        | never
    }
    'pages/posts/find-enough-in-many-worlds.md': {
      routes:
        | '/posts/find-enough-in-many-worlds'
      views:
        | never
    }
    'pages/posts/hello-world.md': {
      routes:
        | '/posts/hello-world'
      views:
        | never
    }
    'pages/posts/private-diary.md': {
      routes:
        | '/posts/private-diary'
      views:
        | never
    }
    'pages/presentations.md': {
      routes:
        | '/presentations'
      views:
        | never
    }
    'pages/private.md': {
      routes:
        | '/private'
      views:
        | never
    }
    'pages/projects.md': {
      routes:
        | '/projects'
      views:
        | never
    }
    'pages/use.md': {
      routes:
        | '/use'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
